
services:
  postgres:
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_DB: "polykek_android"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwe"
      POSTGRES_ROOT_PASSWORD: "qwe"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - './minio-init.sh:/minio-init.sh'
    entrypoint: [ "sh", "-c", "/minio-init.sh" ]
    network_mode: "service:minio"

volumes:
  minio-data:
  postgres-data: